version: "3.8"

networks:
    db-net:
    net:

services:
    db:
        build:
            context: postgres
            dockerfile: Dockerfile
        container_name: personalweb-postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - db-net

    api:
        container_name: personalweb-api
        build:
            context: personalweb-api
            dockerfile: Dockerfile
        volumes:
            - ./personalweb-api:/personalweb-api
            - node_modules:/personalweb-api/node_modules
        networks:
            - net
            - db-net
        depends_on:
            - db

    frontend:
        container_name: personalweb-frontend
        build:
            context: personalweb-frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./personalweb-frontend:/personalweb-frontend
            - node_modules_frontend:/personalweb-frontend/node_modules
        networks:
            - net

    nginx:
        container_name: personalweb-nginx
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - net
        depends_on:
            - api
            - frontend

volumes:
    db_data:
    node_modules:
    node_modules_frontend:
